### ISSUE TITLE
Create new Branch For Flutter Web

### ISSUE THREAD

**Issue by DEVSOG12** [BuildForSDGCohort2/Team-Techbuzs-Frontend#2]
Building for Mobile with JavaScript will affect the build.

A separate branch need to be created for Web

So there will be no mix ups !

**Comment by DEVSOG12** [comment]
Everything else seems okay to complete this!!!

**Comment by dev4larin** [comment]
@DEVSOG12 I think That Should be Okay!! 

You can compile for mobile with 'import 'dart:js'' 

It better to have a separate branch for flutter web.

Considering also flutter web is in beta. It's okay

**Comment by Devjosh1** [comment]
Looks Good to Me!! @DEVSOG12

Nice One There.

**Comment by DEVSOG12** [comment]
This is a Wrap done
